export const GET_ALL_USER_SETTINGS_FETCH =
  "user-profile/GET_ALL_USER_SETTINGS_FETCH";
export const GET_ALL_USER_SETTINGS_SUCCESS =
  "user-profile/GET_ALL_USER_SETTINGS_SUCCESS";
export const GET_ALL_USER_SETTINGS_ERROR =
  "user-profile/GET_ALL_USER_SETTINGS_ERROR";

export const CREATE_DEFAULT_USER_SETTINGS_FETCH =
  "user-profile/CREATE_DEFAULT_USER_SETTINGS_FETCH";

export const CREATE_DEFAULT_USER_SETTINGS_SUCCESS =
  "user-profile/CREATE_DEFAULT_USER_SETTINGS_SUCCESS";

export const CREATE_DEFAULT_USER_SETTINGS_ERROR =
  "user-profile/CREATE_DEFAULT_USER_SETTINGS_ERROR";

export const UPDATE_USER_SETTINGS_FETCH =
  "user-profile/UPDATE_USER_SETTINGS_FETCH";

export const UPDATE_USER_SETTINGS_SUCCESS =
  "user-profile/UPDATE_USER_SETTINGS_SUCCESS";

export const UPDATE_USER_SETTINGS_ERROR =
  "user-profile/UPDATE_USER_SETTINGS_ERROR";
